services:
  Mooc.Tasks.domain.TaskRepository:
    class: ../../../../../Contexts/Mooc/Tasks/infrastructure/persistence/MongoTaskRepository
    arguments: ['@Mooc.Shared.ConnectionManager']

  Mooc.Tasks.domain.ListRepository:
    class: ../../../../../Contexts/Mooc/Lists/infrastructure/persistence/MongoListRepository
    arguments: ['@Mooc.Shared.ConnectionManager']

  Mooc.Tasks.application.TaskCreator:
    class: ../../../../../Contexts/Mooc/Tasks/application/Create/TaskCreator
    arguments:
      ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Boards.domain.BoardRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.Tasks.application.TaskDuplicator:
    class: ../../../../../Contexts/Mooc/Tasks/application/DuplicateTask/TaskDuplicator
    arguments:
      ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Boards.domain.BoardRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.Tasks.TasksByIdFinder:
    class: ../../../../../Contexts/Mooc/Tasks/application/SearchById/TasksByIdFinder
    arguments: ['@Mooc.Tasks.domain.TaskRepository']

  Mooc.Tasks.SearchAllAttachmentsFinder:
    class: ../../../../../Contexts/Mooc/Tasks/application/SearchAllAttachments/SearchAllAttachmentsFinder
    arguments: ['@Mooc.Tasks.domain.ListRepository', '@Mooc.Tasks.domain.TaskRepository']

  Mooc.Tasks.SearchAllAttachmentsQueryHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/SearchAllAttachments/SearchAllAttachmentsQueryHandler
    arguments: ['@Mooc.Tasks.SearchAllAttachmentsFinder']
    tags:
      - { name: 'queryHandler' }

  Mooc.Tasks.SearchByIdTaskQueryHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/SearchById/SearchByIdTaskQueryHandler
    arguments: ['@Mooc.Tasks.TasksByIdFinder']
    tags:
      - { name: 'queryHandler' }

  Mooc.tasks.CreateTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/Create/CreateTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskCreator']
    tags:
      - { name: 'commandHandler' }

  Mooc.Tasks.application.TaskAdderDescription:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddDescription/TaskAdderDescription
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.tasks.AddedDescriptionTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddDescription/AddedDescriptionTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskAdderDescription']
    tags:
      - { name: 'commandHandler' }

  Mooc.Tasks.application.TaskRenamerTitle:
    class: ../../../../../Contexts/Mooc/Tasks/application/Rename/TaskRenamerTitle
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.Tasks.application.TaskChangerPriority:
    class: ../../../../../Contexts/Mooc/Tasks/application/ChangePriority/TaskChangerPriority
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.tasks.ChangePriorityTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/ChangePriority/ChangePriorityTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskChangerPriority']
    tags:
      - { name: 'commandHandler' }

  Mooc.tasks.RenameTitleTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/Rename/RenameTitleTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskRenamerTitle']
    tags:
      - { name: 'commandHandler' }

  Mooc.Tasks.application.TaskAdderCover:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddCover/TaskAdderCover
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.tasks.AddedCoverTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddCover/AddedCoverTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskAdderCover']
    tags:
      - { name: 'commandHandler' }

  Mooc.tasks.DuplicateTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/DuplicateTask/DuplicateTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskDuplicator']
    tags:
      - { name: 'commandHandler' }

  Mooc.Tasks.application.TaskRemoverLabel:
    class: ../../../../../Contexts/Mooc/Tasks/application/RemoveLabel/TaskRemoverLabel
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.tasks.RemovedLabelTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/RemoveLabel/RemovedLabelTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskRemoverLabel']
    tags:
      - { name: 'commandHandler' }

  Mooc.Tasks.application.TaskAdderLabel:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddLabel/TaskAdderLabel
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.tasks.AddedLabelTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddLabel/AddedLabelTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskAdderLabel']
    tags:
      - { name: 'commandHandler' }

  Mooc.Tasks.application.TaskAdderAttachment:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddAttachment/TaskAdderAttachment
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.tasks.AddedAttachmentCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/AddAttachment/AddedAttachmentCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskAdderAttachment']
    tags:
      - { name: 'commandHandler' }

  Mooc.Tasks.application.TaskUpdatorPosition:
    class: ../../../../../Contexts/Mooc/Tasks/application/UpdatePosition/TaskUpdatorPosition
    arguments: ['@Mooc.Tasks.domain.TaskRepository', '@Mooc.Shared.domain.EventBus']

  Mooc.tasks.UpdatePositionTaskCommandHandler:
    class: ../../../../../Contexts/Mooc/Tasks/application/UpdatePosition/UpdatePositionTaskCommandHandler
    arguments: ['@Mooc.Tasks.application.TaskUpdatorPosition']
    tags:
      - { name: 'commandHandler' }
