imports:
  - { resource: ./apps/application.yaml }
  - { resource: ./Courses/application.yaml }
  - { resource: ./CoursesCounter/application.yaml }
  - { resource: ./Users/application.yaml }
  - { resource: ./Boards/application.yaml }
  - { resource: ./Lists/application.yaml }
  - { resource: ./Tasks/application.yaml }
  - { resource: ./Shared/application.yaml }
